name: model_selection
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.4.0
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==0.29.35
      - d3rlpy==2.4.0
      - dataclasses-json==0.6.7
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.13.1
      - fonttools==4.55.3
      - fsspec==2024.2.0
      - glfw==2.8.0
      - grpcio==1.68.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h5py==3.12.1
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.36.1
      - jinja2==3.1.3
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markupsafe==2.1.5
      - marshmallow==3.25.1
      - matplotlib==3.10.0
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - mujoco==2.3.3
      - mujoco-py==2.1.2.14
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - numpy==1.23.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pandas==2.2.3
      - pillow==10.2.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - pycparser==2.22
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.28.1
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - stable-baselines3==2.4.0
      - structlog==25.1.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tifffile==2024.12.12
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tqdm==4.67.1
      - triton==2.1.0
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - urllib3==1.26.13
      - werkzeug==3.1.3
